"""
A collection of utility functions for plotting, simulation ans other supporting madules.
""" 

from .config import (PROJECT_DATA_DIR, 
                     PROJECT_BEH_ALL_DATA_DIR, 
                     FIGURES_DIR,  OUTPUT_CSV_DIR, 
                     PROJECT_REDCAP_DIR, PROJECT_CLIN_EVAL_DIR,
                     PROJECT_HIER_MODEL_DIR, 
                     STAN_DIR, 
                     PROJECT_INDV_MODEL_DIR,
                     SCRATCH_BEH_ALL_DATA_DIR , 
                     SCRATCH_CLIN_EVAL_DIR, 
                     SCRATCH_HIER_MODEL_DIR, 
                     SCRATCH_INDV_MODEL_DIR,
                     COLORS, OPACITY, 
                     PROJECT_RAW_BEH_ALL_FILE, 
                     PROJECT_NoNAN_BEH_ALL_FILE,  
                     PROJECT_CLIN_EVAL_FILE, 
                     SCARTCH_CLIN_EVAL_FILE,
                     PROJECT_CLIN_EVAL_PARAM_FILE, 
                     PROJECT_NoNAN_BEH_REL_IRREL_HIGH_REWARD_OPTION_ALL_FILE, 
                     PROJECT_NoNAN_BEH_REL_IRREL_HIGH_REWARD_OPTION_GROUPBY_ALL_FILE, 
                     PROJECT_NoNAN_BEH_REL_IRREL_HIGH_REWARD_OPTION_GROUPBY_ALL_FILE_MODEL_PARAMETER,
                     PROJECT_RAW_BEH_ALL_PARAMETER_GRAND_TRUTTH_DIR,
                     SCRATCH_RAW_BEH_ALL_PARAMETER_GRAND_TRUTTH_DIR,
                     N_CHAIN, 
                     N_SAMPLES, 
                     N_WARMUP,
                     PARTICIPANTS_PD,
                     PARTICIPANTS_HC,
                     PARTICIPANTS)


from .plotting import (plotRelevantOptionTrial,
                       plotIrrelevantOptionTrial,
                       plotChoiceResponseSubjects,
                       plotChoiceResponse,
                       plotFeatureBias,
                       plotProportionRelIrrelevantHighRewardOption,
                       plot_posterior,
                       plot_hier_kde_posterior,
                       plot_indv_kde_posterior,
                       plot_indv_kde_posterior_seperate)

from .data_utils import (build_behavior_dataframe,
                         calRelevantAndIrrelevantHighRewardOptionTrial)

from .model_utils import (dataStanActClr,
                          config_plot_model,
                          to_pickle,
                          load_pickle,
                          waic_fun,
                          waic_models,
                          MAP_last_axis,
                          participant_list,
                          save_indv_summary_posterior,
                          combine_parameter_highRewardChoice,
                          generating_hier_grand_truth,
                          simulate_hier_rl)

from .random import (simStrategyBehavior)
 

__all__ = ['PROJECT_DATA_DIR', 
           'PROJECT_BEH_ALL_DATA_DIR', 
           'FIGURES_DIR',
           'OUTPUT_CSV_DIR', 
           'PROJECT_REDCAP_DIR', 
           'PROJECT_CLIN_EVAL_DIR',
           'PROJECT_HIER_MODEL_DIR', 
           'STAN_DIR', 
           'PROJECT_INDV_MODEL_DIR',
           'SCRATCH_BEH_ALL_DATA_DIR' , 
           'SCRATCH_CLIN_EVAL_DIR', 
           'SCRATCH_HIER_MODEL_DIR', 
           'SCRATCH_INDV_MODEL_DIR',
           'COLORS', 
           'OPACITY', 
           'PROJECT_RAW_BEH_ALL_FILE', 
           'PROJECT_NoNAN_BEH_ALL_FILE',  
           'PROJECT_CLIN_EVAL_FILE', 
           'SCARTCH_CLIN_EVAL_FILE',
           'PROJECT_CLIN_EVAL_PARAM_FILE', 
           'PROJECT_NoNAN_BEH_REL_IRREL_HIGH_REWARD_OPTION_ALL_FILE', 
           'PROJECT_NoNAN_BEH_REL_IRREL_HIGH_REWARD_OPTION_GROUPBY_ALL_FILE', 
           'PROJECT_NoNAN_BEH_REL_IRREL_HIGH_REWARD_OPTION_GROUPBY_ALL_FILE_MODEL_PARAMETER',
           'PROJECT_RAW_BEH_ALL_PARAMETER_GRAND_TRUTTH_DIR',
           'SCRATCH_RAW_BEH_ALL_PARAMETER_GRAND_TRUTTH_DIR',
           'N_CHAIN', 
           'N_SAMPLES', 
           'N_WARMUP',
           'PARTICIPANTS_PD',
           'PARTICIPANTS_HC',
           'PARTICIPANTS',
           'plotRelevantOptionTrial',
           'plotIrrelevantOptionTrial',
           'plotChoiceResponseSubjects',
           'plotChoiceResponse',
           'plotFeatureBias',
           'plotProportionRelIrrelevantHighRewardOption',
           'plot_posterior',
           'plot_hier_kde_posterior',
           'plot_indv_kde_posterior',
           'plot_indv_kde_posterior_seperate',
           'build_behavior_dataframe',
           'calRelevantAndIrrelevantHighRewardOptionTrial',
           'dataStanActClr',
           'config_plot_model',
           'to_pickle',
           'load_pickle',
           'waic_fun',
           'waic_models',
           'MAP_last_axis',
           'participant_list',
           'save_indv_summary_posterior',
           'combine_parameter_highRewardChoice',
           'generating_hier_grand_truth',
           'simulate_hier_rl',
           'simStrategyBehavior',] 